spring.datasource.url=jdbc:mysql://localhost:3306/ticket_booking_user_db
spring.datasource.username=usrname
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081

jwt.secret=dummySecretKey
jwt.expiration=86400000